CREATE TABLE tags (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
    tag VARCHAR(255) NOT NULL ,
    id_tools BIGINT NOT NULL ,
    FOREIGN KEY (id_tools) REFERENCES tools(id) ON DELETE CASCADE
);